# Generated by Django 4.2.2 on 2023-11-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=10),
        ),
    ]
