# Generated by Django 4.2.2 on 2023-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_tagmodel_mailmodel_blogmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tag',
            field=models.ManyToManyField(to='Blog.tagmodel'),
        ),
    ]
