# Generated by Django 4.2.2 on 2023-11-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_blogmodel_tag_blogmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
